export { CNCLatheHMI } from './CNCLatheHMI';
export { CNCMillHMI } from './CNCMillHMI';
export { PressBrakeHMI } from './PressBrakeHMI';
export { InjectionMoldHMI } from './InjectionMoldHMI';
export { CompressorHMI } from './CompressorHMI';
export { ConveyorHMI } from './ConveyorHMI';
export { WelderHMI } from './WelderHMI';
export { AssemblyRobotHMI } from './AssemblyRobotHMI';
export { GenericMachineHMI } from './GenericMachineHMI';