#!/bin/bash
# ============================================================
#  Sentinel VPS Setup Script
#  Ubuntu 24.04 LTS — Hostinger VPS
#  Run as root: bash setup-vps.sh
# ============================================================

set -e  # Exit on any error

# ── Colors ────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log()    { echo -e "${GREEN}[✓]${NC} $1"; }
warn()   { echo -e "${YELLOW}[!]${NC} $1"; }
error()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }
section(){ echo -e "\n${BLUE}══════════════════════════════════════${NC}"; echo -e "${BLUE}  $1${NC}"; echo -e "${BLUE}══════════════════════════════════════${NC}"; }

# ── Config — Edit before running ──────────────────────────
APP_USER="sentinel"
APP_DIR="/var/www/sentinel"
DOMAIN=""           # e.g. sentinelhq.com  (leave blank to skip SSL)
DB_NAME="sentinel_db"
DB_USER="sentinel_user"
DB_PASS=""          # Will be auto-generated if blank
NODE_VERSION="20"

# ── Pre-flight ────────────────────────────────────────────
section "Pre-flight Checks"

if [ "$EUID" -ne 0 ]; then
  error "Please run as root: sudo bash setup-vps.sh"
fi

if [ -z "$DB_PASS" ]; then
  DB_PASS=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)
  warn "Auto-generated DB password: $DB_PASS"
  warn "Save this password — you'll need it for .env.production"
fi

log "Running as root ✓"
log "Ubuntu version: $(lsb_release -rs)"

# ── System Update ─────────────────────────────────────────
section "System Update"
apt-get update -y && apt-get upgrade -y
apt-get install -y \
  curl wget git unzip build-essential \
  ca-certificates gnupg lsb-release \
  ufw fail2ban htop
log "System packages installed"

# ── Firewall ──────────────────────────────────────────────
section "Firewall (UFW)"
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable
log "Firewall configured (SSH + HTTP + HTTPS)"

# ── Fail2Ban ──────────────────────────────────────────────
section "Fail2Ban"
systemctl enable fail2ban
systemctl start fail2ban
log "Fail2Ban enabled"

# ── Node.js ───────────────────────────────────────────────
section "Node.js ${NODE_VERSION}"
curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
apt-get install -y nodejs
log "Node.js $(node --version) installed"
log "npm $(npm --version) installed"

# ── PM2 ───────────────────────────────────────────────────
section "PM2 Process Manager"
npm install -g pm2
pm2 startup systemd -u root --hp /root
log "PM2 installed: $(pm2 --version)"

# ── PostgreSQL ────────────────────────────────────────────
section "PostgreSQL 16"
apt-get install -y postgresql postgresql-contrib
systemctl enable postgresql
systemctl start postgresql

# Create database and user
sudo -u postgres psql -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASS}';" 2>/dev/null || warn "User ${DB_USER} may already exist"
sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};" 2>/dev/null || warn "Database ${DB_NAME} may already exist"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};"
sudo -u postgres psql -c "ALTER USER ${DB_USER} CREATEDB;"

log "PostgreSQL configured"
log "  Database: ${DB_NAME}"
log "  User:     ${DB_USER}"

# ── Nginx ─────────────────────────────────────────────────
section "Nginx"
apt-get install -y nginx
systemctl enable nginx

# Remove default site
rm -f /etc/nginx/sites-enabled/default

log "Nginx installed: $(nginx -v 2>&1 | grep -o 'nginx/[0-9.]*')"

# ── App User & Directory ──────────────────────────────────
section "App Directory"
mkdir -p ${APP_DIR}
chown -R root:root ${APP_DIR}
log "App directory created: ${APP_DIR}"

# ── Nginx Config ──────────────────────────────────────────
section "Nginx Site Config"

if [ -n "$DOMAIN" ]; then
  NGINX_SERVER_NAME="${DOMAIN} www.${DOMAIN}"
else
  NGINX_SERVER_NAME="_"
  warn "No domain set — using IP-based config. Update DOMAIN in this script to enable SSL."
fi

cat > /etc/nginx/sites-available/sentinel << NGINX_CONF
# Sentinel — Nginx config
# Generated by setup-vps.sh

# Rate limiting
limit_req_zone \$binary_remote_addr zone=api:10m rate=10r/s;
limit_req_zone \$binary_remote_addr zone=auth:10m rate=5r/m;

server {
    listen 80;
    server_name ${NGINX_SERVER_NAME};

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml application/json image/svg+xml;

    # Auth endpoints — stricter rate limiting
    location ~ ^/api/auth {
        limit_req zone=auth burst=5 nodelay;
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }

    # API routes — standard rate limiting
    location /api/ {
        limit_req zone=api burst=20 nodelay;
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }

    # Next.js static files — cached aggressively
    location /_next/static/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_cache_valid 200 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
        proxy_set_header Host \$host;
    }

    # Everything else → Next.js
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 60s;
    }

    # Block common attack paths
    location ~ /\\.ht { deny all; }
    location ~ /\\.git { deny all; }
    location ~ \\.env { deny all; }
}
NGINX_CONF

ln -sf /etc/nginx/sites-available/sentinel /etc/nginx/sites-enabled/sentinel
nginx -t && systemctl reload nginx
log "Nginx configured"

# ── SSL with Certbot (only if domain is set) ──────────────
if [ -n "$DOMAIN" ]; then
  section "SSL Certificate (Let's Encrypt)"
  apt-get install -y certbot python3-certbot-nginx
  certbot --nginx -d ${DOMAIN} -d www.${DOMAIN} \
    --non-interactive --agree-tos \
    --email "admin@${DOMAIN}" \
    --redirect
  log "SSL certificate installed for ${DOMAIN}"

  # Auto-renew
  systemctl enable certbot.timer
  log "Auto-renewal enabled"
fi

# ── Write .env.production ─────────────────────────────────
section "Environment File"
ENV_FILE="${APP_DIR}/.env.production"

if [ ! -f "$ENV_FILE" ]; then
  NEXTAUTH_SECRET=$(openssl rand -base64 32)

  cat > ${ENV_FILE} << ENV_CONF
# ============================================================
# Sentinel — Production Environment
# Generated by setup-vps.sh on $(date)
# ============================================================

# App
NODE_ENV=production
NEXTAUTH_URL=http://${DOMAIN:-147.93.40.212}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# Database
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}?schema=public"

# Email (Hostinger SMTP — update with your credentials)
SMTP_HOST=smtp.hostinger.com
SMTP_PORT=465
SMTP_SECURE=true
SMTP_USER=noreply@yourdomain.com
SMTP_PASS=your_email_password_here
SMTP_FROM="Sentinel <noreply@yourdomain.com>"

# Optional: Stripe (for billing)
# STRIPE_SECRET_KEY=sk_live_...
# STRIPE_WEBHOOK_SECRET=whsec_...
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_live_...
ENV_CONF

  chmod 600 ${ENV_FILE}
  log "Created ${ENV_FILE}"
  warn "IMPORTANT: Update SMTP credentials in ${ENV_FILE}"
else
  warn "${ENV_FILE} already exists — not overwriting"
fi

# ── Summary ───────────────────────────────────────────────
section "Setup Complete! 🎉"

echo ""
echo -e "${GREEN}Database Connection String:${NC}"
echo "  postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}?schema=public"
echo ""
echo -e "${GREEN}Next Steps:${NC}"
echo "  1. Push your code to the server:"
echo "     git clone https://github.com/yourusername/sentinel.git ${APP_DIR}"
echo ""
echo "  2. Copy environment file into your app:"
echo "     cp ${APP_DIR}/.env.production ${APP_DIR}/sentinel/.env.production"
echo ""
echo "  3. Run the deploy script:"
echo "     bash ${APP_DIR}/sentinel/deploy/deploy.sh"
echo ""
if [ -z "$DOMAIN" ]; then
  echo -e "${YELLOW}  4. Set DOMAIN variable in this script and re-run to add SSL${NC}"
fi
echo ""
echo -e "${GREEN}Service Status:${NC}"
echo "  PostgreSQL: $(systemctl is-active postgresql)"
echo "  Nginx:      $(systemctl is-active nginx)"
echo "  PM2:        $(pm2 --version)"
echo ""