import { NextRequest, NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

interface Message {
  role: 'user' | 'assistant';
  content: string;
}

// AI-powered responses for Myncel-related questions
const KNOWLEDGE_BASE: Record<string, string> = {
  'add machine': `To add a machine in Myncel:

1. Go to **Equipment** in the left sidebar
2. Click the **"+ Add Equipment"** button
3. Fill in the machine details:
   - Name and model
   - Location in your facility
   - Serial number (optional)
   - Installation date
4. Click **Save**

Your machine will now appear in your equipment list and you can start tracking maintenance!`,

  'pricing': `Myncel offers flexible pricing:

**Free Trial**: 3 months free to get started
**Starter Plan**: $49/month - Up to 10 machines, basic analytics
**Professional Plan**: $99/month - Up to 50 machines, advanced AI predictions
**Enterprise Plan**: Custom pricing - Unlimited machines, dedicated support

All plans include:
- AI-powered predictive maintenance
- Work order management
- Real-time alerts
- Mobile app access

Would you like me to help you choose the right plan?`,

  'invite team': `To invite team members:

1. Go to **Settings** in the left sidebar
2. Click on **Team** or **Users**
3. Click **"+ Invite User"**
4. Enter their email address
5. Select their role:
   - **Technician**: Can view and update work orders
   - **Manager**: Can manage equipment and view reports
   - **Admin**: Full access to all features
6. Click **Send Invite**

They'll receive an email to join your organization!`,

  'predictive maintenance': `Myncel's AI-powered predictive maintenance works by:

1. **Data Collection**: We track machine usage, runtime hours, and sensor data
2. **Pattern Recognition**: Our AI learns from your equipment's behavior
3. **Failure Prediction**: Get alerts before equipment fails
4. **Smart Scheduling**: Maintenance is scheduled at optimal times

Benefits:
- Reduce unplanned downtime by up to 50%
- Extend equipment lifespan
- Lower maintenance costs
- Improve safety

The system gets smarter over time as it learns more about your equipment!`,

  'work order': `Work orders in Myncel help you track maintenance tasks:

**Creating Work Orders:**
1. Go to **Work Orders** in the sidebar
2. Click **"+ Create Work Order"**
3. Select the equipment and describe the task
4. Assign to a technician
5. Set priority and due date

**Features:**
- Track status (Open, In Progress, Completed)
- Add parts and estimated time
- Attach photos and documents
- Get notifications on updates

Work orders can also be auto-generated by our AI when it detects potential issues!`,

  'alert': `Myncel sends alerts to keep you informed:

**Types of Alerts:**
- 🔧 **Maintenance Due**: Scheduled PM reminders
- ⚠️ **Predictive Alerts**: AI-detected potential failures
- 📉 **Performance Issues**: Anomalies in equipment behavior

**Managing Alerts:**
1. Click the bell icon in the top right
2. View all alerts and their priority
3. Mark as read or create work orders directly

You can customize alert settings in **Settings → Notifications**.`,

  'dashboard': `Your Myncel dashboard provides an overview:

**Key Metrics:**
- Total equipment count
- Active work orders
- Upcoming maintenance
- Recent alerts

**Quick Actions:**
- Add new equipment
- Create work orders
- View reports

**Widgets:**
- Equipment health status
- Maintenance calendar
- Performance trends

The dashboard updates in real-time as your team logs activities!`,

  'report': `Myncel offers comprehensive reporting:

**Available Reports:**
- **Maintenance Summary**: Completed vs. overdue work orders
- **Equipment Health**: Status of all machines
- **Cost Analysis**: Maintenance spending trends
- **Downtime Report**: Equipment availability metrics

**To Generate Reports:**
1. Go to **Reports** in the sidebar
2. Select report type
3. Choose date range
4. Export as PDF or CSV

Reports help you make data-driven maintenance decisions!`,
};

// Analyze conversation to understand context
function analyzeConversation(history: Message[], currentQuestion: string): string {
  if (!history || history.length === 0) return '';
  
  // Get the last few exchanges to understand context
  const recentHistory = history.slice(-6);
  const topics = new Set<string>();
  
  for (const msg of recentHistory) {
    const lower = msg.content.toLowerCase();
    if (lower.includes('machine') || lower.includes('equipment')) topics.add('equipment');
    if (lower.includes('work order') || lower.includes('maintenance')) topics.add('maintenance');
    if (lower.includes('pricing') || lower.includes('plan') || lower.includes('cost')) topics.add('pricing');
    if (lower.includes('team') || lower.includes('invite') || lower.includes('user')) topics.add('team');
    if (lower.includes('alert') || lower.includes('notification')) topics.add('alerts');
    if (lower.includes('report') || lower.includes('analytics')) topics.add('reports');
  }
  
  return Array.from(topics).join(', ');
}

function findBestResponse(question: string, context: string = ''): string {
  const lowerQuestion = question.toLowerCase();
  const hasContext = context && context.length > 0;
  
  // Check for follow-up responses based on context
  if (hasContext) {
    // Handle short responses with context awareness
    if (lowerQuestion === 'yes' || lowerQuestion === 'sure' || lowerQuestion === 'okay' || lowerQuestion === 'ok') {
      if (context.includes('equipment')) {
        return `Great! Let me help you with equipment. Would you like to:

• Add a new machine
• View your current equipment
• Set up maintenance schedules
• Check equipment health status

Just let me know what you'd like to do!`;
      }
      if (context.includes('maintenance')) {
        return `Perfect! For maintenance, I can help you with:

• Creating a new work order
• Viewing upcoming maintenance tasks
• Understanding predictive maintenance alerts
• Scheduling preventive maintenance

What would you like to explore?`;
      }
      if (context.includes('pricing')) {
        return `Excellent! To help you choose the right plan, could you tell me:

• How many machines do you need to track?
• Do you need advanced AI predictions?
• How many team members will use Myncel?

This will help me recommend the best plan for your needs!`;
      }
      if (context.includes('team')) {
        return `Great! For team management, you can:

• Invite new team members
• Set user roles and permissions
• View team activity

Would you like step-by-step instructions for any of these?`;
      }
    }
    
    // Handle "no" or negative responses with context
    if ((lowerQuestion === 'no' || lowerQuestion === 'nope') || 
        (lowerQuestion.includes('not') && lowerQuestion.length < 20)) {
      return `No problem! Is there something else I can help you with? I'm here to assist with:

• Equipment and machine management
• Work orders and maintenance
• Pricing and plans
• Team management
• Reports and analytics

Just ask away!`;
    }
    
    // Handle follow-up questions
    if (lowerQuestion.includes('how about') || lowerQuestion.includes('what about') || 
        lowerQuestion.includes('and the') || lowerQuestion.includes('tell me more')) {
      // Continue the conversation in context
      if (context.includes('equipment')) {
        return `Let me share more about equipment management in Myncel:

**Equipment Features:**
- Track all your machines in one place
- View maintenance history for each machine
- Set up automated maintenance schedules
- Monitor equipment health scores
- Receive predictive alerts

What specific aspect would you like to explore further?`;
      }
      if (context.includes('maintenance')) {
        return `Here's more about maintenance in Myncel:

**Maintenance Capabilities:**
- Preventive maintenance scheduling
- Predictive maintenance using AI
- Work order management
- Maintenance history tracking
- Parts and inventory management

Is there a specific maintenance topic you'd like to dive into?`;
      }
    }
  }
  
  // Check for keyword matches
  for (const [keyword, response] of Object.entries(KNOWLEDGE_BASE)) {
    if (lowerQuestion.includes(keyword)) {
      return response;
    }
  }
  
  // Default responses for common patterns
  if (lowerQuestion.includes('help') || lowerQuestion.includes('how do')) {
    return `I'm here to help! Here are some things I can assist with:

• Adding and managing equipment
• Creating and tracking work orders
• Understanding predictive maintenance
• Pricing and plans
• Team management
• Reports and analytics

What would you like to know more about?`;
  }
  
  if (lowerQuestion.includes('hello') || lowerQuestion.includes('hi ') || lowerQuestion === 'hi') {
    return `Hello! 👋 Welcome to Myncel support. I'm your AI assistant, here to help you get the most out of Myncel. Feel free to ask me anything about the platform!`;
  }
  
  if (lowerQuestion.includes('thank')) {
    return `You're welcome! 😊 Is there anything else I can help you with? I'm here whenever you need assistance with Myncel.`;
  }
  
  if (lowerQuestion.includes('bye') || lowerQuestion.includes('goodbye')) {
    return `Goodbye! 👋 Thanks for chatting with Myncel support. Feel free to come back anytime you have questions. Have a great day!`;
  }
  
  // If we have context but no specific match, acknowledge the conversation
  if (hasContext) {
    const contextTopics = context.split(', ').join(' and ');
    return `I understand we were discussing ${contextTopics}. Could you tell me more about what you need? I'm here to help!

Feel free to ask about:
• Equipment and machines
• Work orders and maintenance
• Pricing and plans
• Team management`;
  }
  
  return `Thanks for your question! I'm an AI assistant and I'll do my best to help.

For specific questions about:
• **Equipment**: Ask about adding, managing, or troubleshooting machines
• **Maintenance**: Learn about work orders and scheduling
• **Features**: Explore what Myncel can do for you
• **Pricing**: Get details on our plans

A human support agent will also review your message and follow up if needed. What else can I help you with?`;
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { question, history = [] } = body as { question: string; history?: Message[] };
    
    if (!question) {
      return NextResponse.json({ error: 'Question is required' }, { status: 400 });
    }
    
    // Analyze conversation context
    const conversationContext = analyzeConversation(history, question);
    const response = findBestResponse(question, conversationContext);
    
    return NextResponse.json({ response });
  } catch (error) {
    console.error('AI chat error:', error);
    return NextResponse.json({ 
      response: "I'm here to help! A support agent will respond to your question shortly." 
    }, { status: 200 });
  }
}